### ISSUE TITLE
Web browser cache issue : the version of the client is the not always the latest if the app is coming from the cache

### ISSUE THREAD

**Issue by szimjer** [bollylu/MediaSearchServer#28]

**Comment by bollylu** [comment]
Check on the client if the version of the TAbout is the same as the version stored in a file on the client server (static file). If not, display a warning message, inviting the user to use Ctrl-F5 to refresh the app.

**Comment by bollylu** [comment]
Alternative solution: prevent the wasm code to stay in the cache. This could be annoying as each startup needs then to reload the whole app.
